disease: myopia
level: -2
dioptria_range: "от -1.25 до -2.0 диоптрий"
description: "Близорукость слабой степени"

object:
  size: "medium"

exercises:
  - name: "circle_right"
    speed: "medium"
  - name: "horizontal"
    speed: "medium"
  - name: "vertical"
    speed: "medium"
  - name: "zigzag"
    speed: "medium"
  - name: "clock"
    speed: "medium"
  - name: "two_diagonals"
    speed: "medium"
